from typing import Optional
import json
import base64
from models import Graph, Node, Edge
from algorithms import BFSResult
from utils.graphml_parser import graphml_parser


class ExportService:
    @staticmethod
    def export_xml(graph: Graph) -> str:
        return graphml_parser.to_graphml(graph)

    @staticmethod
    def export_json(graph: Graph, bfs_result: Optional[BFSResult] = None) -> str:
        export_data = {
            "graph": graph.dict(),
            "bfs_result": bfs_result.dict() if bfs_result else None
        }
        return json.dumps(export_data, indent=2)

    @staticmethod
    def export_cytoscape_json(graph: Graph) -> str:
        elements = []

        for node in graph.nodes.values():
            elements.append({
                "data": {
                    "id": node.id,
                    "label": node.label
                },
                "position": {
                    "x": node.x,
                    "y": node.y
                }
            })

        for edge in graph.edges.values():
            elements.append({
                "data": {
                    "id": edge.id,
                    "source": edge.source,
                    "target": edge.target,
                    "directed": edge.directed,
                    "weight": edge.weight
                }
            })

        return json.dumps({"elements": elements}, indent=2)

    @staticmethod
    def export_markdown_report(
        graph: Graph,
        bfs_result: BFSResult,
        comparison_result: Optional[BFSResult] = None
    ) -> str:
        report_lines = [
            "# BFS Graph Search Report",
            "",
            "## Graph Information",
            f"- **Name**: {graph.name}",
            f"- **Type**: {graph.graph_type}",
            f"- **Nodes**: {len(graph.nodes)}",
            f"- **Edges**: {len(graph.edges)}",
            "",
            "## Search Parameters",
            f"- **Start Node**: {bfs_result.start_node}",
            f"- **Goal Node**: {bfs_result.goal_node}",
            "",
            "## Results",
        ]

        if bfs_result.path:
            path_str = " → ".join(bfs_result.path)
            report_lines.extend([
                f"- **Path Found**: {path_str}",
                f"- **Path Length**: {bfs_result.path_length}",
                f"- **Algorithm Steps**: {bfs_result.steps_count}",
                f"- **Nodes Visited**: {bfs_result.visited_nodes}",
                f"- **Execution Time**: {bfs_result.execution_time_ms} ms",
            ])
        else:
            report_lines.append("- **Result**: No path found between start and goal nodes")

        if comparison_result:
            report_lines.extend([
                "",
                "## Mirror Direction Comparison",
                "",
                "| Metric | Forward | Backward | Difference |",
                "|--------|---------|----------|------------|",
                f"| Path Length | {bfs_result.path_length} | {comparison_result.path_length} | {bfs_result.path_length - comparison_result.path_length} |",
                f"| Algorithm Steps | {bfs_result.steps_count} | {comparison_result.steps_count} | {bfs_result.steps_count - comparison_result.steps_count} |",
                f"| Nodes Visited | {bfs_result.visited_nodes} | {comparison_result.visited_nodes} | {bfs_result.visited_nodes - comparison_result.visited_nodes} |",
                f"| Execution Time (ms) | {bfs_result.execution_time_ms} | {comparison_result.execution_time_ms} | {bfs_result.execution_time_ms - comparison_result.execution_time_ms:.3f} |",
            ])

        report_lines.extend([
            "",
            "## Conclusion",
            "",
            "This report was generated by the BFS Graph Visualizer application.",
            f"Total nodes in graph: {len(graph.nodes)}",
            f"Total edges in graph: {len(graph.edges)}",
        ])

        return "\n".join(report_lines)


export_service = ExportService()
